version: '3.8'

services:
  naval_c2:
    build: .
    container_name: naval-c2-node
    privileged: true
    ports:
      - "2226:22"
    environment:
      - FLAG=${FLAG:-YUVA{d3f3ns1v3_ch1_d3ad10ck_d3f3at3d_l4unch_9902}}
    restart: unless-stopped
