apiVersion: v1
kind: ResourceQuota
metadata:
  name: x08-docker-in-docker-quota
  labels:
    challenge: x08
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "2"
    services: "1"
    count/persistentvolumeclaims: "0"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: x08-docker-in-docker-limits
  labels:
    challenge: x08
spec:
  limits:
  - default:
      cpu: "4"
      memory: 4Gi
    defaultRequest:
      cpu: "500m"
      memory: 512Mi
    type: Container
