apiVersion: apps/v1
kind: Deployment
metadata:
  name: d31-shadow-cron
  labels:
    app: d31-shadow-cron
    challenge-id: d31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d31-shadow-cron
  template:
    metadata:
      labels:
        app: d31-shadow-cron
        challenge-id: d31
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: false    # entrypoint must run as root to set up cron, chown flag, start sshd
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: shadow-cron
          image: d31-shadow-cron:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - SETUID
                - SETGID
                - CHOWN
                - DAC_OVERRIDE
                - NET_BIND_SERVICE    # sshd on 22
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: FLAG
              valueFrom:
                secretKeyRef:
                  name: d31-flag-secret
                  key: flag
