version: '3.8'

services:
  challenge-03-embassy-wiretap:
    build: .
    container_name: embassy-wiretap
    ports:
      - "8042:8042"
    environment:
      - FLAG=${FLAG:-YUVA{h4ck1ng_th3_l4tv3r14n_d1pl0m4t1c_w1r3_5183}}
    restart: unless-stopped
