version: "3.8"

services:
  30-internal-kubernetes:
    build:
      context: .
      dockerfile: Dockerfile
    image: 30-internal-kubernetes:latest
    container_name: 30-internal-kubernetes
    ports:
      - "8090:80"
    environment:
      - FLAG=${FLAG:-YUVA{k8s_rb4c_s3rv1c3_4cc0unt_3x3c_p1v0t_9d82e1}}
      - PORT=80
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    restart: unless-stopped
