version: "3.8"

services:
  39-secret-zero:
    build:
      context: .
      dockerfile: Dockerfile
    image: 39-secret-zero:latest
    container_name: 39-secret-zero
    ports:
      - "8099:80"
    environment:
      - FLAG=${FLAG:-YUVA{s3cr3t_z3r0_m4ch1n3_1d3nt1ty_b00tstr4p_pki_x09}}
      - PORT=80
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    restart: unless-stopped
